name: connectivity_for_web_integration_tests
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  video_player_web: 
    git:
      url: https://github.com/JasmitSingh90/plugins.git
      ref: feature/AudioConfigurationEnabledIOS_Update
      path: packages/video_player/video_player_web
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
